@startuml MyUML
'scale 3   
'크기 조절'

class Point{
-x:int
-y:int
' +Point(x:int,y:int)
'생성자. 없어도 무방함
+getX():int
+setX(x:int):void
+getY():int
+setY(y:int):void
}
class Circle{
-point:Point
-radius : int
+setPoint(Point)
+getPoint():Point
+setRadius(int)
+getRadius():int
+toString():String

}
Point <|--Circle
@enduml